In [329]:
import numpy as np

# The basics

In [330]:
a = np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


In [331]:
b=np.array([[9,0,8,0,7,0],[6,0,5,0,4,0]])
print(b)

[[9 0 8 0 7 0]
 [6 0 5 0 4 0]]


In [332]:
#get dimension
a.ndim

1

In [333]:
b.ndim

2

In [334]:
#get shaope
b.shape

(2, 6)

In [335]:
#get type
a.dtype

dtype('int32')

In [336]:
#get size
a.itemsize

4

In [337]:
#total size
a.nbytes

12

In [338]:
#other method for total size
#a.size * itemsize

# Accessing/Changing ,specific ,elements ,rows ,columns,etc

In [339]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [340]:
#get a specific element[r,c]
a[1,5]

13

In [341]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [342]:
a[:,0]

array([1, 8])

In [343]:
a[:3]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [344]:
a[:5]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [345]:
#getting a little more fancy[start index:,end index: step size]
a[0,1:-1:2]

array([2, 4, 6])

In [346]:
a[1,5]=20
print(a)
a[:,2]=5

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [347]:
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [348]:
a[:,2]=[1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [349]:
b=np.array([[[1,2,],[3,4]],[[5,6],[7,8,]]])

In [350]:
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [351]:
#get specify element(work outside in)
b[0,1]


array([3, 4])

In [352]:
b.shape

(2, 2, 2)

In [353]:
A=np.array([[1,2],[1,3]])

In [354]:
A

array([[1, 2],
       [1, 3]])

In [355]:
A[1,1]

3

In [356]:
#replace
b[:,1,:]=[[4,4],[5,5]]
b

array([[[1, 2],
        [4, 4]],

       [[5, 6],
        [5, 5]]])

# initializing different types of arrays

In [357]:
#all 0s matrix
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [358]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [359]:
np.ones((3,3,2),dtype='int32')

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

In [360]:
#any other number
np.full((2,2),88)

array([[88, 88],
       [88, 88]])

In [361]:
#any other number (full_like)
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [362]:
np.full_like(a,5)

array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

In [363]:
#random decimal numbers
np.random.rand(2,4,3)

array([[[0.54782844, 0.5459734 , 0.09872935],
        [0.42329286, 0.41826121, 0.91434389],
        [0.95353358, 0.21679466, 0.38548811],
        [0.32458694, 0.70262877, 0.39143111]],

       [[0.98163731, 0.10479321, 0.37705626],
        [0.86458941, 0.26986201, 0.58176919],
        [0.92998293, 0.7265653 , 0.59117558],
        [0.99823776, 0.69198929, 0.95561314]]])

In [364]:
np.random.random_sample(a.shape)

array([[0.75269341, 0.83027986, 0.57184108, 0.98359337, 0.90911116,
        0.8506188 , 0.44491728],
       [0.01916979, 0.71576913, 0.19649343, 0.65816529, 0.98491029,
        0.61960824, 0.76921483]])

In [365]:
np.random.rand(4,2)

array([[0.68068482, 0.1724289 ],
       [0.26804345, 0.90259314],
       [0.22963315, 0.54916135],
       [0.52795925, 0.32738286]])

In [366]:
# random integer value
np.random.randint(7,size=(3,3))

array([[0, 1, 4],
       [3, 2, 2],
       [4, 2, 2]])

In [367]:
#indentity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [368]:
#repeat an array
arr = np.array([[1,2,3,4,5]])
r1=np.repeat(arr,4,axis=0)
print(r1)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [369]:
#repeat an array
arr = np.array([[1,2,3,4,5]])
r1=np.repeat(arr,4,axis=1)
print(r1)

[[1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 5 5 5 5]]


In [370]:
#problem
a=np.ones((6,6))
print(a)
z=np.zeros((3,3))
z[1,1]=9
print(z)
a[1:-2,1:-2]=z
print(a)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1. 1.]
 [1. 0. 9. 0. 1. 1.]
 [1. 0. 0. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


#### 

# careful when copying arrays

In [371]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)

[1 2 3]


In [372]:
b=a
b[0]=100
b

array([100,   2,   3])

In [373]:
print(a)

[100   2   3]


In [374]:
b = a.copy()
b[0]=100
b[1]=200
print(b)

[100 200   3]


# Mathematics

In [375]:
a= np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [376]:
a+2

array([3, 4, 5, 6])

In [377]:
a-2

array([-1,  0,  1,  2])

In [378]:
a*2

array([2, 4, 6, 8])

In [379]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [380]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [381]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [382]:
#take sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [383]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# linear algebra

In [384]:
a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)
np.matmul(a,b)
print(np.matmul(a,b))

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


In [385]:
# find the determinant
c=np.identity(3)
np.linalg.det(c)

1.0

# Statistics

In [386]:
stats =np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [387]:
np.min(stats)

1

In [388]:
np.max(stats)

6

In [389]:
np.min(stats,axis=1)

array([1, 4])

In [390]:
np.max(stats,axis=1)

array([3, 6])

In [391]:
np.sum(stats)

21

In [392]:
np.sum(stats,axis=1)

array([ 6, 15])

# Reorganizing Arrays

In [393]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after=before.reshape(2,2,2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [394]:
#vertically stacking vectors
v1= np.array([1,2,3,4,10])
v2 = np.array([5,6,7,8,9])
np.vstack([v1,v2,v2,v2,v2,v2])

array([[ 1,  2,  3,  4, 10],
       [ 5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9]])

In [395]:
# Horizontal stack
h1 = np.ones((2,4))
h2 =np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous
# Load Data from file

In [396]:
filedata=np.genfromtxt('C:/Users/heman/OneDrive/Desktop/data.txt',delimiter=',')
filedata.astype('int32')
filedata=filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


# Boolean Masking Advanced Indexing

In [397]:
filedata>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [398]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [399]:
#you can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [400]:
np.any(filedata>50,axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [401]:
np.any(filedata>50,axis=1)

array([ True,  True,  True])

In [402]:
np.all(filedata>50,axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [403]:
np.all(filedata>50,axis=1)

array([False, False, False])

In [404]:
((filedata>50)&(filedata<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [405]:
(~((filedata>50)&(filedata<100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])