In [1]:
import numpy as np

# The basics

In [21]:
a = np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


In [22]:
b=np.array([[9,0,8,0,7,0],[6,0,5,0,4,0]])
print(b)

[[9 0 8 0 7 0]
 [6 0 5 0 4 0]]


In [23]:
#get dimension
a.ndim

1

In [24]:
b.ndim

2

In [25]:
#get shaope
b.shape

(2, 6)

In [26]:
#get type
a.dtype

dtype('int32')

In [27]:
#get size
a.itemsize

4

In [28]:
#total size
a.nbytes

12

In [31]:
#other method for total size
#a.size * itemsize

# Accessing/Changing ,specific ,elements ,rows ,columns,etc

In [36]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [37]:
#get a specific element[r,c]
a[1,5]

13

In [38]:
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [39]:
a[:,0]

array([1, 8])

In [293]:
a[:3]

array([1, 2, 3])

In [296]:
a[:5]

array([1, 2, 3, 4, 5])

In [43]:
#getting a little more fancy[start index:,end index: step size]
a[0,1:-1:2]

array([2, 4, 6])

In [44]:
a[1,5]=20
print(a)
a[:,2]=5

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [45]:
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [48]:
a[:,2]=[1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [81]:
b=np.array([[[1,2,],[3,4]],[[5,6],[7,8,]]])

In [82]:
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [83]:
#get specify element(work outside in)
b[0,1]


array([3, 4])

In [84]:
b.shape

(2, 2, 2)

In [85]:
A=np.array([[1,2],[1,3]])

In [86]:
A

array([[1, 2],
       [1, 3]])

In [87]:
A[1,1]

3

In [88]:
#replace
b[:,1,:]=[[4,4],[5,5]]
b

array([[[1, 2],
        [4, 4]],

       [[5, 6],
        [5, 5]]])

# initializing different types of arrays

In [89]:
#all 0s matrix
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [91]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [96]:
np.ones((3,3,2),dtype='int32')

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

In [97]:
#any other number
np.full((2,2),88)

array([[88, 88],
       [88, 88]])

In [98]:
#any other number (full_like)
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [99]:
np.full_like(a,5)

array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

In [103]:
#random decimal numbers
np.random.rand(2,4,3)

array([[[0.27615478, 0.37434106, 0.09266494],
        [0.14013955, 0.12447289, 0.28993364],
        [0.4055123 , 0.22434089, 0.90416901],
        [0.53868892, 0.16010172, 0.91900446]],

       [[0.91129085, 0.72106417, 0.59165484],
        [0.1399239 , 0.94544337, 0.89800426],
        [0.60809739, 0.13414703, 0.38468185],
        [0.95452448, 0.86329246, 0.20500808]]])

In [104]:
np.random.random_sample(a.shape)

array([[0.40623521, 0.71362782, 0.89931057, 0.53018402, 0.70677619,
        0.42205993, 0.54665543],
       [0.85370556, 0.86813916, 0.04107376, 0.52977627, 0.27621517,
        0.22007425, 0.6398248 ]])

In [106]:
np.random.rand(4,2)

array([[0.89073086, 0.98404583],
       [0.86091862, 0.21458397],
       [0.4469735 , 0.50564041],
       [0.82563076, 0.03975917]])

In [108]:
# random integer value
np.random.randint(7,size=(3,3))

array([[4, 2, 3],
       [2, 1, 0],
       [2, 1, 4]])

In [114]:
#indentity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [130]:
#repeat an array
arr = np.array([[1,2,3,4,5]])
r1=np.repeat(arr,4,axis=0)
print(r1)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [131]:
#repeat an array
arr = np.array([[1,2,3,4,5]])
r1=np.repeat(arr,4,axis=1)
print(r1)

[[1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 5 5 5 5]]


In [ ]:
#problem
a=np.ones((6,6))
print(a)
z=np.zeros((3,3))
z[1,1]=9
print(z)
a[1:-2,1:-2]=z
print(a)

#### 

# careful when copying arrays

In [157]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)

[1 2 3]


In [158]:
b=a
b[0]=100
b

array([100,   2,   3])

In [152]:
print(a)

[100   2   3]


In [159]:
b = a.copy()
b[0]=100
b[1]=200
print(b)

[100 200   3]


# Mathematics

In [166]:
a= np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [167]:
a+2

array([3, 4, 5, 6])

In [168]:
a-2

array([-1,  0,  1,  2])

In [169]:
a*2

array([2, 4, 6, 8])

In [170]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [171]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [174]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [175]:
#take sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [176]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# linear algebra

In [184]:
a=np.ones((2,3))
print(a)
b=np.full((3,2),2)
print(b)
np.matmul(a,b)
print(np.matmul(a,b))

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]


In [188]:
# find the determinant
c=np.identity(3)
np.linalg.det(c)

1.0

# Statistics

In [189]:
stats =np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [190]:
np.min(stats)

1

In [191]:
np.max(stats)

6

In [192]:
np.min(stats,axis=1)

array([1, 4])

In [193]:
np.max(stats,axis=1)

array([3, 6])

In [194]:
np.sum(stats)

21

In [196]:
np.sum(stats,axis=1)

array([ 6, 15])

# Reorganizing Arrays

In [232]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after=before.reshape(2,2,2)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [241]:
#vertically stacking vectors
v1= np.array([1,2,3,4,10])
v2 = np.array([5,6,7,8,9])
np.vstack([v1,v2,v2,v2,v2,v2])

array([[ 1,  2,  3,  4, 10],
       [ 5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9],
       [ 5,  6,  7,  8,  9]])

In [244]:
# Horizontal stack
h1 = np.ones((2,4))
h2 =np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous
# Load Data from file

In [274]:
filedata=np.genfromtxt('C:/Users/heman/OneDrive/Desktop/data.txt',delimiter=',')
filedata.astype('int32')
filedata=filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


# Boolean Masking Advanced Indexing

In [275]:
filedata>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [276]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [277]:
#you can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [278]:
np.any(filedata>50,axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [282]:
np.any(filedata>50,axis=1)

array([ True,  True,  True])

In [284]:
np.all(filedata>50,axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [285]:
np.all(filedata>50,axis=1)

array([False, False, False])

In [288]:
((filedata>50)&(filedata<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [289]:
(~((filedata>50)&(filedata<100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [303]:
import math


In [305]:
math.sqrt(3)

1.7320508075688772

In [309]:
A = [64, 25, 12, 22, 11] 
  
 
for i in range(len(A)): 
      
     
    min_idx = i 
    for j in range(i+1, len(A)): 
        if A[min_idx] > A[j]: 
            min_idx = j 
              
            
    A[i], A[min_idx] = A[min_idx], A[i] 

In [310]:
print(A)

[11, 12, 22, 25, 64]


In [326]:
def selection(arr):
    for i in range(len(arr)):
        for j in range(i+1,len(arr)):
            if i > j:        
        i, j = j, i
    return arr

IndentationError: expected an indented block (<ipython-input-326-bd20de1dd6e9>, line 5)